### ISSUE TITLE
Any plans on Swift 4 support?

### ISSUE THREAD

**Issue by r-dent** [mkj-is/MKJIcons#1]
Have you any plans to port this repo to Swift 4 in the near future? Maybe regenerate from PaintCode?

**Comment by mkj-is** [comment]
Will look into it, hopefully this won't be so complicated.

**Comment by mkj-is** [comment]
Hello @r-dent, I finished the update to Swift 4 and updated the example too so it works nicely on iPhone X too, hopefully this is useful to you.

Also, I was somehow planning to reqrite everything to CAShapeLayers, but this project is just a fun one, so if you have any ideas or pull requests, they are welcome.
